name: Build and Attach Docker Image to Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Клонируем код из репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Сборка Docker-образа
      - name: Build Docker image
        run: |
          docker build -t habr-automation .

      # Шаг 3: Упаковка Docker-образа в tar
      - name: Save Docker image to tar
        run: |
          docker save habr-automation > habr-automation.tar

      # Шаг 4: Загрузка в релиз
      - name: Upload Docker image to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./habr-automation.tar
          asset_name: habr-automation.tar
          asset_content_type: application/x-tar
